# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-20 23:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mezzanine.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0003_auto_20150527_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.Page')),
                ('content', mezzanine.core.fields.RichTextField(verbose_name='Content')),
                ('heading', models.CharField(help_text='Put your name here or something', max_length=200)),
                ('sub_heading', mezzanine.core.fields.RichTextField(help_text='Maybe a brief description of who you are or something', max_length=1000)),
                ('avatar', mezzanine.core.fields.FileField(blank=True, help_text='A high res photo that will appear on the homepage', max_length=255, null=True, verbose_name='Image')),
                ('banner', mezzanine.core.fields.FileField(blank=True, help_text='A high res photo that will appear on the homepage', max_length=255, null=True, verbose_name='Image')),
                ('copyright', mezzanine.core.fields.RichTextField(max_length=1000)),
                ('section_2_heading', models.CharField(default='about', help_text='Put your name here or something', max_length=200)),
                ('section_2_blurb', mezzanine.core.fields.RichTextField(help_text='A brief blurb about this section.', max_length=1000)),
            ],
            options={
                'ordering': ('_order',),
                'verbose_name': 'Home page',
                'verbose_name_plural': 'Home pages',
            },
            bases=('pages.page', models.Model),
        ),
    ]
