# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-20 23:39
from __future__ import unicode_literals

from django.db import migrations
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('read_only', '0002_homepage_section_2_sub_heading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='avatar',
            field=mezzanine.core.fields.FileField(blank=True, help_text='A high res photo that will appear on the homepage', max_length=255, null=True, verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='banner',
            field=mezzanine.core.fields.FileField(blank=True, help_text='A high res photo that will appear on the homepage', max_length=255, null=True, verbose_name='Banner'),
        ),
    ]
